In [1]:
import numpy as np
import pandas as pd
from itertools import combinations_with_replacement
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('C:\\Users\\hp\\Desktop\\A1_2020A&PS0155H_2020A7PS1700H_2020A7PS0189H\\fods_1.csv')
data.head()

MLOGP  RDCHI  quantitative response of LC50
0  2.419  1.225                          3.740
1  2.638  1.401                          4.330
2  5.799  2.930                          7.019
3  5.453  2.887                          6.723
4  4.068  2.758                          5.979

In [3]:
X=data.iloc[:,0:2]
X=X.values
#X[0].max()
X[1].max()

2.638

In [4]:
y=data.iloc[:,2:3]
y=y.values 
y.max()

10.047

In [5]:
def dw0(X,y,weight,lambda_,q):
    n=X.shape[0]
    dE=0.0
    for i in range(n):
        dE-=y[i]-(weight[1]*X[i][0]+weight[2]*X[i][1]+weight[0])
    return dE

def dw1(X,y,weight,lambda_,q):
    n=X.shape[0]
    dE=(lambda_/2)*q*pow(weight[1],q-1)*pow(-1,np.sign(weight[1]))
    for i in range(n):
        dE-=(y[i]-(weight[1]*X[i][0]+weight[2]*X[i][1]+weight[0]))*X[i][0]
    return dE

def dw2(X,y,weight,lambda_,q):
    n=X.shape[0]
    dE=(lambda_/2)*q*pow(weight[2],q-1)*pow(-1,np.sign(weight[2]))
    for i in range(n):
        dE-=(y[i]-(weight[1]*X[i][0]+weight[2]*X[i][1]+weight[0]))*X[i][1]
    return dE

In [6]:
def make_model_regularized(X,y,q,learning_rate,lambda_,iterations):
    weight=np.ones(3)
    for i in range(iterations):
        temp=weight
        weight[0]=weight[0]-learning_rate*dw0(X,y,temp,lambda_,q)
        weight[1]=weight[1]-learning_rate*dw1(X,y,temp,lambda_,q)
        weight[2]=weight[2]-learning_rate*dw2(X,y,temp,lambda_,q)
    return weight

In [7]:
def regularized_error(X,y,weight,lambda_,q):
    n=X.shape[0]
    E=0.0
    for i in range(n):
        E+=(1/2)*((y[i]-(weight[1]*X[i][0]+weight[2]*X[i][1]+weight[0]))**2)+(lambda_/2)*((pow(abs(weight[1]),q))+pow(abs(weight[2]),q))
    return E

In [8]:
def total_error(X,y,weight):
    n=X.shape[0]
    E=0.0
    for i in range(n):
        E+=(1/2)*((y[i]-(weight[1]*X[i][0]+weight[2]*X[i][1]+weight[0]))**2)
    return E

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=70,shuffle=True)

In [10]:
m=make_model_regularized(X_train,y_train,0.5,0.0001,0.1,1000)
E1=regularized_error(X_test,y_test,m,0.1,0.5)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.1 and power=0.5 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,1,0.0001,0.1,1000)
E1=regularized_error(X_test,y_test,m,0.1,1)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.1 and power=1.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,2,0.0001,0.1,1000)
E1=regularized_error(X_test,y_test,m,0.1,2)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.1 and power=2.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,4,0.0001,0.1,1000)
E1=regularized_error(X_test,y_test,m,0.1,4)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.1 and power=4.0 is as follows")
print(m)
print(E1)
print(E2)

The value of weights,regularized error and total error for lambda=0.1 and power=0.5 is as follows
[2.28526104 0.42916985 0.54642812]
[98.14041195]
[90.47166117]
The value of weights,regularized error and total error for lambda=0.1 and power=1.0 is as follows
[2.28511156 0.42917164 0.54648635]
[95.83853202]
[90.47241308]
The value of weights,regularized error and total error for lambda=0.1 and power=2.0 is as follows
[2.28504887 0.4291635  0.54651794]
[93.12861174]
[90.47286431]
The value of weights,regularized error and total error for lambda=0.1 and power=4.0 is as follows
[2.28521135 0.42915231 0.54646142]
[91.14920683]
[90.47219439]


In [11]:
m=make_model_regularized(X_train,y_train,0.5,0.0001,0.15,1000)
E1=regularized_error(X_test,y_test,m,0.15,0.5)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.15 and power=0.5 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,1,0.0001,0.15,1000)
E1=regularized_error(X_test,y_test,m,0.15,1)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.15 and power=1.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,2,0.0001,0.15,1000)
E1=regularized_error(X_test,y_test,m,0.15,2)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.15 and power=2.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,4,0.0001,0.15,1000)
E1=regularized_error(X_test,y_test,m,0.15,4)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.15 and power=4.0 is as follows")
print(m)
print(E1)
print(E2)

The value of weights,regularized error and total error for lambda=0.15 and power=0.5 is as follows
[2.2851123  0.42917733 0.5464813 ]
[101.97579382]
[90.47232378]
The value of weights,regularized error and total error for lambda=0.15 and power=1.0 is as follows
[2.28488806 0.42918001 0.54656866]
[98.52337884]
[90.4734523]
The value of weights,regularized error and total error for lambda=0.15 and power=2.0 is as follows
[2.2847939 0.4291678 0.5466161]
[94.45866694]
[90.47413014]
The value of weights,regularized error and total error for lambda=0.15 and power=4.0 is as follows
[2.28503752 0.42915101 0.54653136]
[91.4890171]
[90.47312514]


In [12]:
m=make_model_regularized(X_train,y_train,0.5,0.0001,0.5,1000)
E1=regularized_error(X_test,y_test,m,0.5,0.5)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.5 and power=0.5 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,1,0.0001,0.5,1000)
E1=regularized_error(X_test,y_test,m,0.5,1)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.5 and power=1.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,2,0.0001,0.5,1000)
E1=regularized_error(X_test,y_test,m,0.5,2)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.5 and power=2.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,4,0.0001,0.5,1000)
E1=regularized_error(X_test,y_test,m,0.5,4)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.5 and power=4.0 is as follows")
print(m)
print(E1)
print(E2)

The value of weights,regularized error and total error for lambda=0.5 and power=0.5 is as follows
[2.28407142 0.42922971 0.54685342]
[128.82988867]
[90.47696884]
The value of weights,regularized error and total error for lambda=0.5 and power=1.0 is as follows
[2.28332354 0.42923863 0.54714481]
[117.33129038]
[90.48074576]
The value of weights,regularized error and total error for lambda=0.5 and power=2.0 is as follows
[2.28300677 0.42919776 0.54730425]
[103.78622665]
[90.48302848]
The value of weights,regularized error and total error for lambda=0.5 and power=4.0 is as follows
[2.28381641 0.42914175 0.54702274]
[93.87473776]
[90.47967592]


In [13]:
m=make_model_regularized(X_train,y_train,0.5,0.0001,0.001,1000)
E1=regularized_error(X_test,y_test,m,0.001,0.5)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.001 and power=0.5 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,1,0.0001,0.001,1000)
E1=regularized_error(X_test,y_test,m,0.001,1)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.001 and power=1.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,2,0.0001,0.001,1000)
E1=regularized_error(X_test,y_test,m,0.001,2)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.001 and power=2.0 is as follows")
print(m)
print(E1)
print(E2)
m=make_model_regularized(X_train,y_train,4,0.0001,0.001,1000)
E1=regularized_error(X_test,y_test,m,0.001,4)
E2=total_error(X_test,y_test,m)
print("The value of weights,regularized error and total error for lambda=0.001 and power=4.0 is as follows")
print(m)
print(E1)
print(E2)

The value of weights,regularized error and total error for lambda=0.001 and power=0.5 is as follows
[2.28555559 0.42915504 0.5463228 ]
[90.54703288]
[90.47034991]
The value of weights,regularized error and total error for lambda=0.001 and power=1.0 is as follows
[2.2855541  0.42915506 0.54632338]
[90.52400873]
[90.47035742]
The value of weights,regularized error and total error for lambda=0.001 and power=2.0 is as follows
[2.28555347 0.42915498 0.5463237 ]
[90.49690731]
[90.47036192]
The value of weights,regularized error and total error for lambda=0.001 and power=4.0 is as follows
[2.2855551  0.42915486 0.54632313]
[90.47712043]
[90.47035522]
